spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: sdvkit
    password: sdvkit-roottoor
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate.format_sql: true
server:
  port: 8081
  error.include-message: always