dev:
  datasource.url: jdbc:postgresql://localhost:5432/blog
  datasource.username: sdvkit
  datasource.password: sdvkit-roottoor
  datasource.driver: org.postgresql.Driver
  log.file: src/main/resources/log/logfile.log