server:
  port: ${dev.server.port}
  error.include-message: always
spring:
  profiles:
    active: dev
  datasource:
    url: ${dev.datasource.url}
    username: ${dev.datasource.username}
    password: ${dev.datasource.password}
    driver-class-name: ${dev.datasource.driver}
  jpa:
    generate-ddl: false
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate.format_sql: true